"""
Django settings for spots project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

from decouple import Csv, config
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# Error monitoring — off unless SENTRY_DSN is set in .env, so local dev
# and CI (which never set it) are completely unaffected. This is what
# actually surfaces the errors behind the friendly 404/403/500 pages;
# without it a production crash is silent until a user happens to
# report it. send_default_pii is left off since tasks/tickets carry
# real customer names, phone numbers and emails in request data.
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=config('SENTRY_ENVIRONMENT', default='production' if not DEBUG else 'development'),
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.0, cast=float),
        send_default_pii=False,
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'rest_framework',
    'rest_framework.authtoken',
    'reference',
    'customers',
    'people',
    'tasks',
    'reports',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'spots.middleware.TechnicianLocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last — axes needs to see what every other middleware
    # already did to the request/response before it decides whether
    # this attempt counts toward a lockout.
    'axes.middleware.AxesMiddleware',
]

# django-axes: locks an IP address out after repeated failed logins
# (the library's own default key, left as-is deliberately) — since
# every username in this app is predictable (supervisor1, manager1,
# ...) an attacker isn't limited to guessing one account's password,
# they can just as easily spray one guess across many usernames, which
# a per-username-only limit wouldn't catch. Nothing else in the
# codebase throttles login attempts. AxesStandaloneBackend must come
# first, ahead of Django's own ModelBackend, so a locked-out attempt
# is rejected before password checking even runs.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_TEMPLATE = 'axes_lockout.html'
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False
# `manage.py test` runs every existing test through Client.login(),
# which calls authenticate() with no request object at all —
# AxesStandaloneBackend requires one and raises rather than silently
# allowing the login through, so every test using that shortcut would
# otherwise error out. Off by default under the test runner; the one
# test class that actually exercises lockout behaviour
# (people.tests.LoginLockoutTests) turns it back on for itself via
# @override_settings.
AXES_ENABLED = 'test' not in sys.argv

ROOT_URLCONF = 'spots.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'people.context_processors.role_permissions',
                'people.context_processors.active_country',
                'spots.context_processors.static_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'spots.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='spots'),
        'USER': config('DB_USER', default='spots'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {'connect_timeout': 5},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Arabic and English from the start — see CLAUDE.md.

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# All timestamps are stored in UTC; convert to local time only at display.
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (technician-uploaded photos and videos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email (customer feedback requests)
# Defaults to printing to the console so local dev and tests never need
# real credentials — set EMAIL_BACKEND and the rest in .env to send for real.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@profitsportssolutions.com')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth
# https://docs.djangoproject.com/en/5.2/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# The app has no JS that reads the CSRF cookie (tokens go out via the
# server-rendered {% csrf_token %} hidden field), so there's no reason for
# it to be script-readable — keep it HttpOnly to limit what a future XSS
# could do with it.
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Off by default even in production — only turn these on once the app
    # is actually served over HTTPS (directly or via a proxy that sets
    # X-Forwarded-Proto), since enabling SECURE_SSL_REDIRECT behind a proxy
    # that doesn't forward that header causes an infinite redirect loop.
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# API (for the technician/staff mobile app)
# Token auth only — the app has no cookies to carry, and every request
# already needs to say who it's acting as. Same RolePermission checks as
# the web views underneath (see api/permissions.py), not a separate model.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
