# Generated by Django 5.2.17 on 2026-09-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('portal_url', models.URLField(blank=True, help_text='where the office requests spare parts', verbose_name='portal URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('iso_code', models.CharField(max_length=2, verbose_name='ISO code')),
                ('timezone', models.CharField(help_text='IANA name, e.g. Asia/Riyadh', max_length=50, verbose_name='timezone')),
                ('currency_code', models.CharField(max_length=3, verbose_name='currency code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='stable key, never changes', max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('category', models.CharField(choices=[('installation', 'Installation'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='category')),
                ('requires_photos', models.BooleanField(default=False, verbose_name='requires photos')),
                ('requires_signature', models.BooleanField(default=False, verbose_name='requires signature')),
                ('checklist_template', models.JSONField(blank=True, default=dict, help_text='fields the report form shows for this type', verbose_name='checklist template')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'task type',
                'verbose_name_plural': 'task types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='reference.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
