# Generated by Django 5.2.17 on 2026-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('cardio', 'Cardio')], default='other', help_text="cardio lines don't count toward the technician certification bar", max_length=10, verbose_name='category'),
        ),
    ]
