# Generated by Django 5.2.17 on 2026-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_cardio_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'conduct area',
                'verbose_name_plural': 'conduct areas',
                'ordering': ['name'],
            },
        ),
    ]
