# Generated by Django 5.2.17 on 2026-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_seed_conduct_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='task_prefix',
            field=models.CharField(blank=True, help_text='overrides the ISO code as the task-number prefix — e.g. KSA or UAE, since those are how people here actually refer to the country, not the ISO code. Leave blank to just use the ISO code.', max_length=5, verbose_name='task number prefix'),
        ),
    ]
