# Generated by Django 5.2.17 on 2026-09-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_seed_task_prefixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='brand',
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('other', 'Basic'), ('cardio', 'Cardio')], default='other', help_text="cardio skills don't count toward the technician certification bar", max_length=10, verbose_name='category'),
        ),
    ]
