# Generated by Django 5.2.17 on 2026-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_add_online_meeting_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('other', 'Basic'), ('cardio', 'Advanced')], default='other', help_text="advanced skills don't count toward the technician certification bar", max_length=10, verbose_name='category'),
        ),
    ]
