# Generated by Django 5.2.17 on 2026-09-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_taskasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(help_text='what the technician found', verbose_name='findings')),
                ('action_taken', models.TextField(blank=True, verbose_name='action taken')),
                ('resolved', models.BooleanField(verbose_name='resolved')),
                ('labour_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='labour hours')),
                ('customer_name', models.CharField(help_text='who signed', max_length=150, verbose_name='customer name')),
                ('signature_url', models.URLField(blank=True, verbose_name='signature URL')),
                ('submitted_at', models.DateTimeField(verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'work report',
                'verbose_name_plural': 'work reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, verbose_name='part code')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
                ('currency_code', models.CharField(help_text='never store an amount without its currency', max_length=3, verbose_name='currency code')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='reports.workreport', verbose_name='report')),
            ],
            options={
                'verbose_name': 'part used',
                'verbose_name_plural': 'parts used',
                'ordering': ['report', 'part_code'],
            },
        ),
    ]
