# Generated by Django 5.2.17 on 2026-09-16 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tasks', '0003_alter_task_task_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=43, unique=True, verbose_name='token')),
                ('requested_at', models.DateTimeField(verbose_name='requested at')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'customer feedback',
                'verbose_name_plural': 'customer feedback',
                'ordering': ['-requested_at'],
            },
        ),
    ]
