# Generated by Django 5.2.17 on 2026-09-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_customerfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='rejection_reason',
        ),
    ]
