# Generated by Django 5.2.17 on 2026-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_workreport_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='signature_waived_reason',
            field=models.TextField(blank=True, help_text='filled in when the customer was not available to sign', verbose_name='why there is no signature'),
        ),
    ]
