# Generated by Django 5.2.17 on 2026-09-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('segment', models.CharField(choices=[('gym', 'Gym'), ('hotel', 'Hotel'), ('club', 'Club'), ('other', 'Other')], max_length=20, verbose_name='segment')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='reference.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('access_notes', models.TextField(blank=True, help_text='gate codes, best hours', verbose_name='access notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ['customer__name', 'name'],
            },
        ),
    ]
