# Generated by Django 5.2.17 on 2026-09-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='free text from the plate', max_length=150, verbose_name='model name')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='serial number')),
                ('installed_on', models.DateField(blank=True, null=True, verbose_name='installed on')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='warranty end')),
                ('status', models.CharField(choices=[('active', 'Active'), ('faulty', 'Faulty'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='status')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='reference.brand', verbose_name='brand')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='customers.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['site__name', 'model_name'],
                'indexes': [models.Index(fields=['site', 'status'], name='customers_a_site_id_45c2f7_idx')],
            },
        ),
    ]
