# Generated by Django 5.2.17 on 2026-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='where a feedback request goes after a report is approved', max_length=254, verbose_name='contact email'),
        ),
    ]
