# Generated by Django 5.2.17 on 2026-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_site_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='used for a site that has no contact of its own — the single-branch case, or a chain where every site shares the same one', max_length=254, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='contact name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='contact phone'),
        ),
    ]
