# Generated by Django 5.2.17 on 2026-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', help_text='for the portal login, if this customer has one', max_length=2, verbose_name='language'),
        ),
    ]
