# Generated by Django 5.2.17 on 2026-09-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, help_text='this company’s account/reference code, if it has one', max_length=50, verbose_name='customer code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='where replacement parts should be delivered, if different from the site itself — a warehouse or head office', verbose_name='shipping address'),
        ),
    ]
