# Generated by Django 5.2.17 on 2026-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_code_customer_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='set when staff creates the login with a temporary system-generated password — the customer is walked through setting their own password and confirming their contact details once, the first time they sign in, before reaching the rest of the portal', verbose_name='must change password'),
        ),
    ]
