# Generated by Django 5.2.17 on 2026-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deactivation_reason',
            field=models.CharField(blank=True, help_text='why this customer was deactivated — contract ended, closed down, etc.', max_length=255, verbose_name='deactivation reason'),
        ),
    ]
