# Generated by Django 5.2.17 on 2026-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='site',
            name='location_source',
            field=models.CharField(blank=True, choices=[('office', 'Entered by the office'), ('arrival', 'Set by the first arrival')], max_length=10, verbose_name='location source'),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
