# Generated by Django 5.2.17 on 2026-10-09 18:27

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_site_location'),
    ]

    operations = [
        # Trigram indexes for "contains" searches (spots/indexes.py); the
        # tasks app's search indexes depend on this migration for it too.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('serial_no'), name='gin_trgm_ops'), name='asset_serial_trgm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('model_name'), name='gin_trgm_ops'), name='asset_model_trgm'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='customer_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='site_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('address'), name='gin_trgm_ops'), name='site_address_trgm'),
        ),
    ]
