# Generated by Django 5.2.17 on 2026-09-06 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('people', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(help_text='per country', max_length=30, verbose_name='task number')),
                ('min_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum level')),
                ('description', models.TextField(blank=True, help_text='what the customer reported', verbose_name='description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], max_length=20, verbose_name='priority')),
                ('source', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('internal', 'Internal')], max_length=20, verbose_name='source')),
                ('is_warranty', models.BooleanField(blank=True, null=True, verbose_name='is warranty')),
                ('billing_type', models.CharField(choices=[('warranty', 'Warranty'), ('contract', 'Contract'), ('chargeable', 'Chargeable'), ('goodwill', 'Goodwill')], max_length=20, verbose_name='billing type')),
                ('reported_at', models.DateTimeField(verbose_name='reported at')),
                ('promised_at', models.DateTimeField(blank=True, help_text='what the customer is owed', null=True, verbose_name='promised at')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='the day the supervisor planned', null=True, verbose_name='scheduled for')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='status')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='reference.brand', verbose_name='brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='reference.skill', verbose_name='required skill')),
                ('site', models.ForeignKey(help_text='the only certain field at creation', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='customers.site', verbose_name='site')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='reference.tasktype', verbose_name='task type')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('helper', 'Helper')], max_length=20, verbose_name='role')),
                ('assigned_at', models.DateTimeField(verbose_name='assigned at')),
                ('is_active', models.BooleanField(default=True, help_text='false once replaced', verbose_name='active')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('end_reason', models.CharField(blank=True, choices=[('sick', 'Sick'), ('leave', 'Leave'), ('overloaded', 'Overloaded'), ('skill_mismatch', 'Skill mismatch'), ('customer_request', 'Customer request'), ('emergency', 'Emergency'), ('vehicle', 'Vehicle'), ('other', 'Other')], help_text='required on reassignment — one tap, never free text', max_length=20, verbose_name='end reason')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'task assignment',
                'verbose_name_plural': 'task assignments',
                'ordering': ['task', '-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_kind', models.CharField(choices=[('file', 'File'), ('link', 'Link')], max_length=10, verbose_name='storage kind')),
                ('url', models.URLField(verbose_name='URL')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], max_length=20, verbose_name='media type')),
                ('purpose', models.CharField(choices=[('fault', 'Fault'), ('serial_plate', 'Serial plate'), ('before', 'Before'), ('after', 'After')], max_length=20, verbose_name='purpose')),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('supervisor', 'Supervisor'), ('technician', 'Technician')], max_length=20, verbose_name='source')),
                ('uploaded_at', models.DateTimeField(verbose_name='uploaded at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'task attachment',
                'verbose_name_plural': 'task attachments',
                'ordering': ['task', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('rescheduled', 'Rescheduled'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('blocked', 'Blocked'), ('started', 'Started'), ('completed', 'Completed'), ('report_submitted', 'Report submitted'), ('report_rejected', 'Report rejected'), ('report_approved', 'Report approved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='event type')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('corrected_at', models.DateTimeField(blank=True, help_text="supervisor's correction", null=True, verbose_name='corrected at')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('corrected_by', models.ForeignKey(blank=True, help_text='supervisors only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_event_corrections', to=settings.AUTH_USER_MODEL, verbose_name='corrected by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task event',
                'verbose_name_plural': 'task events',
                'ordering': ['task', 'occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'promised_at'], name='tasks_task_status_b292c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['site', 'status'], name='tasks_task_site_id_f9c814_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_for', 'status'], name='tasks_task_schedul_b0dfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['technician', 'is_active'], name='tasks_taska_technic_4de568_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'lead')), fields=('task',), name='one_active_lead_per_task'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', 'occurred_at'], name='tasks_taske_task_id_b83dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='tasks_taske_event_t_31113e_idx'),
        ),
    ]
