# Generated by Django 5.2.17 on 2026-09-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_asset'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('repaired', 'Repaired'), ('replaced', 'Replaced'), ('not_repairable', 'Not repairable'), ('inspected_ok', 'Inspected OK')], max_length=20, verbose_name='outcome')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assets', to='customers.asset', verbose_name='asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assets', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task asset',
                'verbose_name_plural': 'task assets',
                'ordering': ['task', 'asset'],
                'indexes': [models.Index(fields=['asset'], name='tasks_taska_asset_i_b049ce_idx')],
            },
        ),
    ]
