# Generated by Django 5.2.17 on 2026-09-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(help_text='auto-generated per country, e.g. AE-0001', max_length=30, unique=True, verbose_name='task number'),
        ),
    ]
