# Generated by Django 5.2.17 on 2026-09-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='roughly how long the job should take — shown as an estimated finish time', max_digits=4, null=True, verbose_name='estimated hours'),
        ),
    ]
