# Generated by Django 5.2.17 on 2026-09-17 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_seed_task_prefixes'),
        ('tasks', '0004_task_estimated_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('internal', 'Internal'), ('portal', 'Customer ticket')], max_length=20, verbose_name='source'),
        ),
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='company / customer name')),
                ('site_description', models.CharField(help_text='branch name or address, as the customer describes it', max_length=150, verbose_name='site / location')),
                ('contact_name', models.CharField(max_length=150, verbose_name='contact name')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('description', models.TextField(help_text='what the customer reported', verbose_name='description')),
                ('submitted_at', models.DateTimeField(verbose_name='submitted at')),
                ('status', models.CharField(choices=[('new', 'New'), ('converted', 'Converted to task'), ('dismissed', 'Dismissed')], default='new', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('dismissal_reason', models.CharField(blank=True, max_length=255, verbose_name='dismissal reason')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_tickets', to='reference.country', verbose_name='country')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'customer ticket',
                'verbose_name_plural': 'customer tickets',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
