# Generated by Django 5.2.17 on 2026-09-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_seed_manage_tickets_permission'),
        ('tasks', '0005_alter_task_source_customerticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assigned at'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='who is handling this — a technician or a supervisor, not necessarily who converts it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='people.technician', verbose_name='assigned to'),
        ),
    ]
