# Generated by Django 5.2.17 on 2026-09-17 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_customerticket_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_notified_at',
            field=models.DateTimeField(blank=True, help_text='when the customer was last emailed about the scheduled visit — never automatic', null=True, verbose_name='schedule notified at'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_notified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_schedule_notified', to=settings.AUTH_USER_MODEL, verbose_name='schedule notified by'),
        ),
    ]
