# Generated by Django 5.2.17 on 2026-09-17 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_seed_manage_customers_permission'),
        ('tasks', '0008_alter_taskevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='who is handling this — a supervisor or manager, not necessarily who converts it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='people.technician', verbose_name='assigned to'),
        ),
    ]
