# Generated by Django 5.2.17 on 2026-09-18 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_customerticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='notes',
            field=models.TextField(blank=True, verbose_name='anything else we should know'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='serial_numbers',
            field=models.TextField(default='', help_text='please list each affected machine on a new line', verbose_name='serial number(s)'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='site_address',
            field=models.TextField(default='', verbose_name='gym address'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='gym name'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='contact email address'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='contact_name',
            field=models.CharField(max_length=150, verbose_name='full contact name'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='contact_phone',
            field=models.CharField(max_length=30, verbose_name='contact phone number'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='description',
            field=models.TextField(help_text='please describe the issue for each machine separately (mention the serial number for each one)', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='site_description',
            field=models.CharField(help_text='branch name, as the customer describes it', max_length=150, verbose_name='site / location'),
        ),
        migrations.CreateModel(
            name='CustomerTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='file')),
                ('uploaded_at', models.DateTimeField(verbose_name='uploaded at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.customerticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket attachment',
                'verbose_name_plural': 'ticket attachments',
                'ordering': ['ticket', 'uploaded_at'],
            },
        ),
    ]
