# Generated by Django 5.2.17 on 2026-09-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_unseed_review_reports_permission'),
        ('tasks', '0010_customerticket_notes_customerticket_serial_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible_supervisor',
            field=models.ForeignKey(blank=True, help_text='who is accountable for staffing this task — not necessarily who created it, and not the same as the technician actually assigned to do the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_responsible_for', to='people.technician', verbose_name='responsible supervisor'),
        ),
    ]
