# Generated by Django 5.2.17 on 2026-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_responsible_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='pak_reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PAK reference number'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='shipping tracking number'),
        ),
        migrations.AddField(
            model_name='task',
            name='pak_reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PAK reference number'),
        ),
        migrations.AddField(
            model_name='task',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='shipping tracking number'),
        ),
    ]
