# Generated by Django 5.2.17 on 2026-09-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_user'),
        ('tasks', '0013_customerticket_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='set automatically — at submission if the customer was logged in, otherwise once the ticket is converted to a task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.customer', verbose_name='customer'),
        ),
    ]
