# Generated by Django 5.2.17 on 2026-09-19 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_customerticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='factory_offer',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='factory offer'),
        ),
        migrations.AddField(
            model_name='task',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='task',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='quotation'),
        ),
    ]
