# Generated by Django 5.2.17 on 2026-09-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_factory_offer_task_invoice_task_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
            ],
            options={
                'verbose_name': 'task document',
                'verbose_name_plural': 'task documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
    ]
