# Generated by Django 5.2.17 on 2026-09-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_taskdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDocument',
        ),
        migrations.CreateModel(
            name='TaskFactoryOffer',
            fields=[
            ],
            options={
                'verbose_name': 'factory offer',
                'verbose_name_plural': 'factory offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskQuotation',
            fields=[
            ],
            options={
                'verbose_name': 'quotation',
                'verbose_name_plural': 'quotations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
    ]
