# Generated by Django 5.2.17 on 2026-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_delete_taskdocument_taskfactoryoffer_taskinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='factory_offer_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='factory offer uploaded at'),
        ),
        migrations.AddField(
            model_name='task',
            name='invoice_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoice uploaded at'),
        ),
        migrations.AddField(
            model_name='task',
            name='quotation_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='quotation uploaded at'),
        ),
    ]
