# Generated by Django 5.2.17 on 2026-09-20 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_factory_offer_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer')], max_length=10, verbose_name='sender')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(verbose_name='sent at')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replies_sent', to=settings.AUTH_USER_MODEL, verbose_name='sent by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.customerticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket reply',
                'verbose_name_plural': 'ticket replies',
                'ordering': ['sent_at'],
            },
        ),
    ]
