# Generated by Django 5.2.17 on 2026-09-20 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_reply_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='attachment'),
        ),
    ]
