# Generated by Django 5.2.17 on 2026-09-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_ticketreply_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='close_reason',
            field=models.CharField(blank=True, help_text='resolved without needing a task — advice given, handled by phone, etc.', max_length=255, verbose_name='close reason'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('converted', 'Converted to task'), ('dismissed', 'Dismissed'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
