# Generated by Django 5.2.17 on 2026-09-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_taskevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('rescheduled', 'Rescheduled'), ('delay_notice', 'Delay notice sent'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('blocked', 'Blocked'), ('started', 'Started'), ('paused', 'Paused for the day'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('report_submitted', 'Report submitted'), ('report_rejected', 'Report rejected'), ('report_approved', 'Report approved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled'), ('negligence', 'Negligence reported')], max_length=30, verbose_name='event type'),
        ),
    ]
