# Generated by Django 5.2.17 on 2026-09-21 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_taskevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeliveryNote',
            fields=[
            ],
            options={
                'verbose_name': 'delivery note',
                'verbose_name_plural': 'delivery notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_note',
            field=models.FileField(blank=True, help_text='the shipment paperwork — uploaded once the parts arrive', null=True, upload_to='task_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='delivery note'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_note_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery note uploaded at'),
        ),
    ]
