# Generated by Django 5.2.17 on 2026-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_taskdeliverynote_task_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='shipping_company',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL'), ('fedex', 'FedEx'), ('ups', 'UPS'), ('aramex', 'Aramex'), ('tnt', 'TNT'), ('local_courier', 'Local courier'), ('other', 'Other')], max_length=20, verbose_name='shipping company'),
        ),
        migrations.AddField(
            model_name='task',
            name='shipping_company',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL'), ('fedex', 'FedEx'), ('ups', 'UPS'), ('aramex', 'Aramex'), ('tnt', 'TNT'), ('local_courier', 'Local courier'), ('other', 'Other')], max_length=20, verbose_name='shipping company'),
        ),
    ]
