# Generated by Django 5.2.17 on 2026-09-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_technician_deactivation_reason'),
        ('tasks', '0025_customerticket_shipping_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_time_locked',
            field=models.BooleanField(default=False, help_text='true once a manager sets both the day and the exact time together — a supervisor can no longer change scheduled_for directly and must request a change', verbose_name='schedule time locked'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='set by a manager scheduling day-only — the day is fixed while scheduled_for stays empty until a supervisor fills in the time', null=True, verbose_name='scheduled date'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('rescheduled', 'Rescheduled'), ('delay_notice', 'Delay notice sent'), ('schedule_change_requested', 'Schedule change requested'), ('schedule_change_approved', 'Schedule change approved'), ('schedule_change_denied', 'Schedule change denied'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('blocked', 'Blocked'), ('started', 'Started'), ('paused', 'Paused for the day'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('report_submitted', 'Report submitted'), ('report_rejected', 'Report rejected'), ('report_approved', 'Report approved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled'), ('negligence', 'Negligence reported')], max_length=30, verbose_name='event type'),
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_scheduled_for', models.DateTimeField(verbose_name='requested scheduled for')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_note', models.CharField(blank=True, max_length=255, verbose_name='review note')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_change_requests', to='people.technician', verbose_name='requested by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_change_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'schedule change request',
                'verbose_name_plural': 'schedule change requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
