# Generated by Django 5.2.17 on 2026-09-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_task_schedule_time_locked_task_scheduled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, verbose_name='product code')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='serial number')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task product',
                'verbose_name_plural': 'task products',
                'ordering': ['task', 'product_code'],
            },
        ),
    ]
