# Generated by Django 5.2.17 on 2026-09-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_language'),
        ('tasks', '0027_taskproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='site',
            field=models.ForeignKey(blank=True, help_text='set when a logged-in customer picked one of their own registered sites — carries straight through to the resulting task with no re-matching, and only an admin can change it once set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_time_locked',
            field=models.BooleanField(default=False, help_text='set automatically — true whenever a manager is the one who last set scheduled_for; a supervisor doing so leaves it false. Locked means a supervisor can no longer change scheduled_for directly and must request a change', verbose_name='schedule time locked'),
        ),
    ]
