# Generated by Django 5.2.17 on 2026-09-25 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_customerticket_site_alter_task_schedule_time_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='note')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_internal_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='tasks.customerticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket internal note',
                'verbose_name_plural': 'ticket internal notes',
                'ordering': ['created_at'],
            },
        ),
    ]
