# Generated by Django 5.2.17 on 2026-09-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_ticketinternalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='customer_code',
            field=models.CharField(blank=True, help_text='set automatically for a logged-in customer, from their own account', max_length=50, verbose_name='customer code'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='where replacement parts should be delivered, if different from the site itself', verbose_name='shipping address'),
        ),
    ]
