# Generated by Django 5.2.17 on 2026-09-25 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_customerticket_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='is_quotation',
            field=models.BooleanField(default=False, help_text='sends the dedicated quotation email (with the attachment) instead of a plain reply notice — staff only', verbose_name='is quotation'),
        ),
        migrations.AlterField(
            model_name='customerticketattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_reply_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='attachment'),
        ),
    ]
