# Generated by Django 5.2.17 on 2026-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_ticketreply_is_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='purpose',
            field=models.CharField(choices=[('fault', 'Fault'), ('serial_plate', 'Serial plate'), ('before', 'Before'), ('after', 'After'), ('delivery_note', 'Delivery note'), ('written_report', 'Written report'), ('other', 'Other')], max_length=20, verbose_name='purpose'),
        ),
    ]
