# Generated by Django 5.2.17 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_customerticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproduct',
            name='arm',
            field=models.CharField(blank=True, max_length=100, verbose_name='arm color'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='frame',
            field=models.CharField(blank=True, max_length=100, verbose_name='frame color'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='padding',
            field=models.CharField(blank=True, max_length=100, verbose_name='padding color'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='replacement',
            field=models.CharField(blank=True, help_text='which machine this was swapped in for, if the one ordered wasn’t available', max_length=150, verbose_name='replacement'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='trim',
            field=models.CharField(blank=True, max_length=100, verbose_name='trim color'),
        ),
    ]
