# Generated by Django 5.2.17 on 2026-09-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_taskproduct_arm_taskproduct_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_ticket', 'New ticket'), ('new_reply', 'New reply')], max_length=20, verbose_name='kind')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='seen at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.customerticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket notification',
                'verbose_name_plural': 'ticket notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
