# Generated by Django 5.2.17 on 2026-09-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_ticketnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='is_quotation',
        ),
    ]
