# Generated by Django 5.2.17 on 2026-09-26 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_code_customer_shipping_address'),
        ('tasks', '0036_remove_ticketreply_is_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinternalnote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_internal_note_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='customerticket',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='set automatically at submission — every ticket is submitted by a logged-in customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.customer', verbose_name='customer'),
        ),
    ]
