# Generated by Django 5.2.17 on 2026-09-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_ticketinternalnote_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='seen at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task notification',
                'verbose_name_plural': 'task notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
