# Generated by Django 5.2.17 on 2026-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_tasknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invoice_visible_to_supervisor',
            field=models.BooleanField(default=False, help_text='documents are manager-tier by default — turn this on for a specific task when a supervisor is the one collecting payment on site and needs to see the invoice', verbose_name='show invoice to the supervisor'),
        ),
    ]
