# Generated by Django 5.2.17 on 2026-09-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_task_invoice_visible_to_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('pending_supervisor_review', 'Pending supervisor review'), ('completed', 'Completed'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='new', max_length=25, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('rescheduled', 'Rescheduled'), ('delay_notice', 'Delay notice sent'), ('schedule_change_requested', 'Schedule change requested'), ('schedule_change_approved', 'Schedule change approved'), ('schedule_change_denied', 'Schedule change denied'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('blocked', 'Blocked'), ('started', 'Started'), ('paused', 'Paused for the day'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('report_submitted', 'Report submitted'), ('report_rejected', 'Report rejected'), ('supervisor_approved', 'Approved by supervisor'), ('report_approved', 'Report approved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled'), ('negligence', 'Negligence reported')], max_length=30, verbose_name='event type'),
        ),
    ]
