# Generated by Django 5.2.17 on 2026-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_alter_task_status_alter_taskevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reported_serial_numbers',
            field=models.TextField(blank=True, help_text='copied from the ticket at conversion, one per line — the machines the customer named before anyone visited. The team can find more on site; those go on the work report as usual, not here.', verbose_name='reported serial numbers'),
        ),
    ]
