# Generated by Django 5.2.17 on 2026-09-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_seed_warehouse_manager_role'),
        ('tasks', '0041_task_reported_serial_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(verbose_name='sent at')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='sent by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task message',
                'verbose_name_plural': 'task messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='seen at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='tasks.taskmessage', verbose_name='message')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_message_notifications', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'task message recipient',
                'verbose_name_plural': 'task message recipients',
                'constraints': [models.UniqueConstraint(fields=('message', 'technician'), name='unique_task_message_recipient')],
            },
        ),
    ]
