# Generated by Django 5.2.17 on 2026-09-27 21:05

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_taskmessage_taskmessagerecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerticketattachment',
            name='file',
            field=models.FileField(upload_to=tasks.models._ticket_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models._ticket_reply_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='attachment'),
        ),
    ]
