# Generated by Django 5.2.17 on 2026-09-27 21:23

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_alter_customerticketattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivery_note',
            field=models.FileField(blank=True, help_text='the shipment paperwork — uploaded once the parts arrive', null=True, upload_to=tasks.models._task_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='delivery note'),
        ),
        migrations.AlterField(
            model_name='task',
            name='factory_offer',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models._task_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='factory offer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models._task_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models._task_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='quotation'),
        ),
        migrations.AlterField(
            model_name='ticketinternalnote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models._ticket_internal_note_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm', 'pdf'])], verbose_name='attachment'),
        ),
    ]
