# Generated by Django 5.2.17 on 2026-10-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_alter_rolepermission_permission_and_more'),
        ('tasks', '0045_taskevent_correction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnotification',
            name='kind',
            field=models.CharField(choices=[('new_ticket', 'New ticket'), ('new_reply', 'New reply'), ('escalation_decided', 'Escalation decided')], max_length=20, verbose_name='kind'),
        ),
        migrations.CreateModel(
            name='TicketEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='internal — never shown to the customer', verbose_name='reason')),
                ('customer_message', models.TextField(blank=True, help_text='optional — shown on the customer’s ticket page', verbose_name='message to the customer')),
                ('decision', models.CharField(choices=[('pending', 'Awaiting decision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('instructions', 'Instructions given')], default='pending', max_length=20, verbose_name='decision')),
                ('decision_note', models.TextField(blank=True, verbose_name='decision note')),
                ('escalated_at', models.DateTimeField(verbose_name='escalated at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_raised', to='people.technician', verbose_name='escalated by')),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to='people.technician', verbose_name='escalated to')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tasks.customerticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket escalation',
                'verbose_name_plural': 'ticket escalations',
                'ordering': ['-escalated_at'],
            },
        ),
    ]
