# Generated by Django 5.2.17 on 2026-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_ticketnotification_kind_ticketescalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('leave', 'Leave'), ('overloaded', 'Overloaded'), ('skill_mismatch', 'Skill mismatch'), ('customer_request', 'Customer request'), ('emergency', 'Emergency'), ('vehicle', 'Vehicle'), ('left_company', 'Left the company'), ('other', 'Other')], help_text='required on reassignment — one tap, never free text', max_length=20, verbose_name='end reason'),
        ),
    ]
