# Generated by Django 5.2.17 on 2026-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_alter_taskassignment_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='labour_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='this person’s own hours on the job, when not the report’s: a helper’s, or a lead’s before a handover', max_digits=5, null=True, verbose_name='labour hours'),
        ),
    ]
