# Generated by Django 5.2.17 on 2026-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_task_assignment_labour_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, help_text='worked out at the tap, from the site location at that time', null=True, verbose_name='distance from the site (m)'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='location accuracy (m)'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='location_status',
            field=models.CharField(blank=True, choices=[('at_site', 'At the site'), ('away', 'Not at the site'), ('no_location', 'No location sent'), ('site_unknown', 'Site location not set')], max_length=15, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
