# Generated by Django 5.2.17 on 2026-10-09 18:27

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_search_indexes'),
        ('tasks', '0049_task_event_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerticket',
            index=models.Index(fields=['country', 'status', '-submitted_at'], name='ticket_country_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('ticket_number'), name='gin_trgm_ops'), name='ticket_number_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('company_name'), name='gin_trgm_ops'), name='ticket_company_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('site_description'), name='gin_trgm_ops'), name='ticket_site_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('site_address'), name='gin_trgm_ops'), name='ticket_address_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('pak_reference_number'), name='gin_trgm_ops'), name='ticket_pak_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('contact_name'), name='gin_trgm_ops'), name='ticket_contact_trgm'),
        ),
        migrations.AddIndex(
            model_name='customerticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('contact_phone'), name='gin_trgm_ops'), name='ticket_phone_trgm'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('task_number'), name='gin_trgm_ops'), name='task_number_trgm'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('pak_reference_number'), name='gin_trgm_ops'), name='task_pak_trgm'),
        ),
        migrations.AddIndex(
            model_name='taskproduct',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('serial_number'), name='gin_trgm_ops'), name='taskproduct_serial_trgm'),
        ),
    ]
