# Generated by Django 5.2.17 on 2026-10-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('stock', 'Stock request'), ('vendor', 'Vendor follow-up'), ('other', 'Other internal')], default='customer', max_length=10, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='opened_by',
            field=models.ForeignKey(blank=True, help_text='the staff member who opened it — empty when the customer did', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_opened', to=settings.AUTH_USER_MODEL, verbose_name='opened by'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='source',
            field=models.CharField(choices=[('portal', 'Customer portal'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='portal', max_length=10, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='subject',
            field=models.CharField(blank=True, help_text='internal tickets only', max_length=200, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='vendor'),
        ),
    ]
