# Generated by Django 5.2.17 on 2026-09-06 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], help_text='per person, not per country', max_length=2, verbose_name='language')),
                ('role', models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=20, verbose_name='role')),
                ('employment_type', models.CharField(choices=[('staff', 'Staff'), ('freelance', 'Freelance')], max_length=20, verbose_name='employment type')),
                ('has_transport', models.BooleanField(default=False, verbose_name='has transport')),
                ('can_carry_large', models.BooleanField(default=False, help_text='can move a treadmill motor or locker bank', verbose_name='can carry large equipment')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='hired on')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='reference.country', verbose_name='country')),
                ('user', models.OneToOneField(blank=True, help_text='for Microsoft SSO later', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'technician',
                'verbose_name_plural': 'technicians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='level')),
                ('set_on', models.DateField(verbose_name='set on')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('set_by', models.ForeignKey(help_text='which supervisor decided', on_delete=django.db.models.deletion.PROTECT, related_name='levels_set', to='people.technician', verbose_name='set by')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_skills', to='reference.skill', verbose_name='skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'technician skill',
                'verbose_name_plural': 'technician skills',
                'ordering': ['technician__full_name', 'skill__brand__name'],
                'constraints': [models.UniqueConstraint(fields=('technician', 'skill'), name='unique_technician_skill')],
            },
        ),
    ]
