# Generated by Django 5.2.17 on 2026-09-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_available',
            field=models.BooleanField(default=True, help_text='whether this technician can currently be assigned work — separate from is_active', verbose_name='available'),
        ),
        migrations.AddField(
            model_name='technician',
            name='unavailable_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('other', 'Other')], max_length=20, verbose_name='unavailable reason'),
        ),
    ]
