# Generated by Django 5.2.17 on 2026-09-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_technician_skill_assessment'),
        ('reference', '0006_conductarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianConductAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='level')),
                ('source', models.CharField(choices=[('self', 'Self-rated'), ('supervisor', 'Supervisor')], max_length=10, verbose_name='source')),
                ('set_on', models.DateField(verbose_name='set on')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('conduct_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_assessments', to='reference.conductarea', verbose_name='conduct area')),
                ('set_by', models.ForeignKey(help_text='the technician himself for a self-rating, the supervisor for a review', on_delete=django.db.models.deletion.PROTECT, related_name='conduct_assessments_made', to='people.technician', verbose_name='set by')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_assessments', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'technician conduct assessment',
                'verbose_name_plural': 'technician conduct assessments',
                'ordering': ['-set_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='level')),
                ('source', models.CharField(choices=[('self', 'Self-rated'), ('supervisor', 'Supervisor')], help_text='a self-rating is a starting guess — only a supervisor review counts toward certification', max_length=10, verbose_name='source')),
                ('set_on', models.DateField(verbose_name='set on')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('conduct_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_ratings', to='reference.conductarea', verbose_name='conduct area')),
                ('set_by', models.ForeignKey(help_text='the technician himself for a self-rating, the supervisor for a review', on_delete=django.db.models.deletion.PROTECT, related_name='conduct_ratings_set', to='people.technician', verbose_name='set by')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_ratings', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'technician conduct rating',
                'verbose_name_plural': 'technician conduct ratings',
                'ordering': ['technician__full_name', 'conduct_area__name'],
                'constraints': [models.UniqueConstraint(fields=('technician', 'conduct_area'), name='unique_technician_conduct')],
            },
        ),
    ]
