# Generated by Django 5.2.17 on 2026-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_technicianconductassessment_technicianconduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=20, verbose_name='role')),
                ('permission', models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('review_reports', 'View and review work reports')], max_length=30, verbose_name='permission')),
                ('allowed', models.BooleanField(default=False, verbose_name='allowed')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'ordering': ['permission', 'role'],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')],
            },
        ),
    ]
