# Generated by Django 5.2.17 on 2026-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_seed_manage_tickets_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_notify_on_reschedule', models.BooleanField(default=False, help_text='off by default — a supervisor sends it deliberately from task detail instead', verbose_name='email the customer automatically when a task is rescheduled')),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
            },
        ),
    ]
