# Generated by Django 5.2.17 on 2026-09-17 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='photo',
            field=models.FileField(blank=True, help_text='shown on the roster, boards, and task detail', null=True, upload_to='technician_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('review_reports', 'View and review work reports'), ('manage_tickets', 'Review customer-submitted tickets'), ('manage_technicians', 'Edit technician profile photos')], max_length=30, verbose_name='permission'),
        ),
    ]
