# Generated by Django 5.2.17 on 2026-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_seed_manage_technicians_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('review_reports', 'View and review work reports'), ('manage_tickets', 'Review customer-submitted tickets'), ('manage_technicians', 'Edit technician profile photos'), ('manage_customers', 'Add and view customers and sites')], max_length=30, verbose_name='permission'),
        ),
    ]
