# Generated by Django 5.2.17 on 2026-09-19 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_alter_rolepermission_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianskill',
            options={'ordering': ['technician__full_name', 'skill__name'], 'verbose_name': 'technician skill', 'verbose_name_plural': 'technician skills'},
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='evidence',
            field=models.FileField(blank=True, help_text='photo or video of the technician actually performing this repair', null=True, upload_to='skill_evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='evidence'),
        ),
        migrations.AddField(
            model_name='technicianskillassessment',
            name='evidence',
            field=models.FileField(blank=True, help_text='photo or video of the technician actually performing this repair', null=True, upload_to='skill_evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='evidence'),
        ),
    ]
