# Generated by Django 5.2.17 on 2026-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_alter_technicianskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='deactivation_reason',
            field=models.CharField(blank=True, help_text='why this technician was deactivated — resigned, terminated, etc.', max_length=255, verbose_name='deactivation reason'),
        ),
    ]
