# Generated by Django 5.2.17 on 2026-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_technician_deactivation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
    ]
