# Generated by Django 5.2.17 on 2026-09-27 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_backfill_support_manager_permission_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('manage_tickets', 'Review customer-submitted tickets'), ('manage_technicians', 'Add technicians and edit their profile photos'), ('manage_customers', 'Add and view customers and sites'), ('view_machines', 'View machines and their task/ticket history')], max_length=30, verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, help_text="a manager creates this from the technician's Edit screen, same as a customer's portal login", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
