# Generated by Django 5.2.17 on 2026-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_seed_view_machines_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('support_manager', 'Technical Support Manager'), ('warehouse_manager', 'Warehouse Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('support_manager', 'Technical Support Manager'), ('warehouse_manager', 'Warehouse Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
    ]
