# Generated by Django 5.2.17 on 2026-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_seed_warehouse_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='set when a manager creates the login with a temporary system-generated password — they must set their own the first time they sign in, before reaching anything else', verbose_name='must change password'),
        ),
    ]
