# Generated by Django 5.2.17 on 2026-09-27 21:23

import django.core.validators
import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_technician_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='photo',
            field=models.FileField(blank=True, help_text='shown on the roster, boards, and task detail', null=True, upload_to=people.models._technician_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='technicianskill',
            name='evidence',
            field=models.FileField(blank=True, help_text='photo or video of the technician actually performing this repair', null=True, upload_to=people.models._skill_evidence_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='evidence'),
        ),
        migrations.AlterField(
            model_name='technicianskillassessment',
            name='evidence',
            field=models.FileField(blank=True, help_text='photo or video of the technician actually performing this repair', null=True, upload_to=people.models._skill_evidence_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'mp4', 'mov', 'webm'])], verbose_name='evidence'),
        ),
    ]
