# Generated by Django 5.2.17 on 2026-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_alter_technician_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('manage_tickets', 'Review customer-submitted tickets'), ('manage_technicians', "Edit technicians' details and profile photos"), ('manage_customers', 'View and edit customers and sites'), ('view_machines', 'View machines and their task/ticket history')], max_length=30, verbose_name='permission'),
        ),
    ]
