# Generated by Django 5.2.17 on 2026-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_alter_rolepermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('view_dashboard', 'View dashboard'), ('view_tasks', 'View task list, task detail, and week view'), ('create_tasks', 'Create new tasks'), ('assign_tasks', 'Assign technicians to tasks'), ('view_technicians', 'View technician roster and boards'), ('review_skills', 'Confirm technician skill levels'), ('manage_tickets', 'Review customer-submitted tickets'), ('manage_technicians', "Edit technicians' details and profile photos"), ('manage_customers', 'View and edit customers and sites'), ('view_machines', 'View machines and their task/ticket history'), ('decide_escalated_tickets', 'Decide tickets escalated to them')], max_length=30, verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('support_manager', 'Technical Support Manager'), ('warehouse_manager', 'Warehouse Manager'), ('operations_manager', 'Operations Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('support_manager', 'Technical Support Manager'), ('warehouse_manager', 'Warehouse Manager'), ('operations_manager', 'Operations Manager'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
    ]
