# Generated by Django 5.2.17 on 2026-10-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_seed_operations_manager_role'),
        ('reference', '0019_set_saturday_sunday_weekends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visiting_trips', to='reference.country', verbose_name='country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['-start_date'],
            },
        ),
    ]
