# Generated by Django 5.2.17 on 2026-10-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_seed_manage_parts_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='push token')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='people.technician', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'push device',
                'verbose_name_plural': 'push devices',
            },
        ),
    ]
